#ifndef _PROB_PARM_H_
#define _PROB_PARM_H_

#include <AMReX_REAL.H>
#include <AMReX_GpuQualifiers.H>
#include <AMReX_GpuMemory.H>

struct ProbParmDevice
{
  amrex::GpuArray<amrex::Real, NUM_SPECIES> massfrac = {1.0};
  amrex::Real p_0 = 1.0;
  amrex::Real p_r = 1.0;
  amrex::Real rho_0 = 1.0;
  amrex::Real rho_r = 1.0;
  amrex::Real u_0 = 0.0;
  amrex::Real u_r = 1.0;
  amrex::Real v_0 = 0.0;
  amrex::Real v_r = 0.0;
  amrex::Real width = 0.1;
  amrex::Real Mach_shock = 2.0;
  amrex::Real Mach_in = 2.0;  
  amrex::Real inflow_time = 0.0;
  amrex::Real gamma = 1.4;
  amrex::Real Rsp = amrex::Real(8.31446261815324e7/28.97);
  amrex::Real out_width = 0.1;
  amrex::Real out_loend = 0.0;
  int iprobe = 0;
  int jprobe = 0;
  amrex::Real in_loend = 0.0;
  int isout_lox = 0;

  std::string pres_file = "pressuredata.txt";
};

struct ProbParmHost
{
  ProbParmHost() {}
};

#endif
